name: Test & Analyse

on:
  push:
    branches: [ main, develop, release, release/* ]
  pull_request:
    branches: [ main, develop, release, release/* ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: smplphp/playground
          verbose: true

      - name: Run mutation tests
        run: vendor/bin/infection
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: Run psalm analysis
        run: vendor/bin/psalm --threads=2 --output-format=github --shepherd

      - name: Run phpstan analysis
        run: vendor/bin/phpstan analyse
